<!-- CSS se cargara en el template, primero carga el view luego el template -->
<?php Tag::css('../bower_components/datatables.net-bs/css/dataTables.bootstrap.min') ?>
<script type="text/javascript">
  $(document).ready(function() {
    var table = $('#tabla_productos').DataTable( {
      "ajax": {
               "url": "listar_usuarios",
               "dataSrc":"",
               "dataType": "json",
               "cache": false,
             },
      dom: 'Bfrtip',
      "buttons": [
         {"extend": 'excel', "text":'<i class="fa fa-download" aria-hidden="true"></i>&nbsp; &nbsp; Exportar Excel',"className": 'btn btn-success pull-center'}
      ],
      "columns": [
      	  { "data": "nombre" },
      	  { "data": "rbd" },
          { "data": "colegio" },
          { "data": "cargo" },
          { "data": "telefono" },
          { "data": "correo" },
          { "data": "fecha"},
          { "data": "acciones" }
      ]
    });
    $("#tabla_productos").on("click", ".eliminar", function(){
      var id = $(this).attr("value");
      console.log(id);
      swal({
        title: '¿Estas seguro de eliminar?',
        text: 'Si eliminas este usuario, no se podrá recuperar la información',
        type: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Si, eliminar',
        cancelButtonText: 'No, eliminar usuario'
      }).then((result) => {
        //console.log(result);
        if (result.value) {
          $.ajax({
            type: 'POST',
            cache: false,
            url: 'eliminar',
            data: {'id':id},
            success: function(result){
              console.log(result);
              if(result === 1){
                swal({
                      type: 'success',
                      title: 'Usuario eliminado',
                      text: 'Recargando información...',
                      timer: 2000,
                      onOpen: () => {
                        swal.showLoading()
                      }
                    }).then((result) => {
                      if (result.dismiss === 'timer') {
                        $('#tabla_productos').DataTable().ajax.reload();
                      }
                    });
              }else{
                swal("Error", "No se ha podido eliminar este usuario", "error");
              }
            }
          })
        } else if (result.dismiss === 'cancel') {
          swal(
            'Cancelado',
            'Este usuario no ha sido eliminado',
            'info'
          )
        }
      });
    });

    $(".agregar").click(function(){
      location.href = "https://localhost/smcompra/administrador/alumnos/crear/";
    })
  });
</script>
<div class="row">
  <div class="col-md-12">
    <div class="box box-danger">
      <div class="box-header">
        <i class="fa fa-users hidden"></i>
        <h3 class="box-title pull-left"> Lista de Usuarios </h3>
        <br>
        <br>
        <button class="btn btn-success agregar pull-right">Agregar nuevo usuario</button>
        <div class="table-responsive col-md-12">
          <table id="tabla_productos" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
		                <th>Nombre</th>
            		    <th>RBD</th>
            		    <th>Colegio</th>
                    <th>Cargo</th>
                    <th>Teléfono</th>
                    <th>Correo</th>
                    <th>Fecha</th>
                    <th>Acciones</th>
                </tr>
            </thead>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
