<br>
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <div class="card text-white bg-info mb-3" style="max-width: 100%">
      <div class="card-body">
        <h4 class="card-title">Entrar en la plataforma</h4>
        <div class="form-group">
          <?php View::content() ?>
          <?php echo Form::open() ?>
          <input name="mode" type="hidden" value="auth">
            <label>Usuario</label>
            <?php echo Form::text('correo', 'class="form-control" placeholder="tucorreo@correo.com"') ?>
            <label>Clave</label>
            <?php echo Form::pass('clave', 'class="form-control" placeholder="**********"') ?>
            <br>
            <?php echo Form::submit('Entrar', 'class="btn btn-success"') ?>
          <?php echo Form::close() ?>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-3"></div>
</div>
