<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Administrador de Eventos - Ediciones SM</h3>
        <div class="box-tools pull-right">
          <!-- Buttons, labels, and many other things can be placed here! -->
          <!-- Here is a label for example -->
          <span class="label label-primary">+</span>
        </div>
        <!-- /.box-tools -->
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <p>En esta plataforma podrás hacer las siguientes funcionalidades:</p>
        <p>
          Modificar la configuración básica de la plataforma web.
        </p>
        <p>
          Modificar el programa según evento solicitado.
        </p>
        <p>
          Crear, agregar y editar conferencistas que participan en dicho evento.
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-2"></div>
</div>
