<div class="row">
  <div class="col-md-12">
    <div class="box box-danger">
      <div class="box-header">
        <i class="fa fa-building hidden"></i>
        <h3 class="box-title"> Editar Colegio </h3>
        <div class="box-body">
          <form id="crear_colegio" >
            <input id="colegio" type="hidden" value="<?php echo $colegio->id ?>">
            <h4>RBD</h4>
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-user" style="color:red"></i></span>
              <input id="rbd" type="text" class="form-control" value="<?php echo $colegio->rbd ?>" placeholder="Ingrese RBD del colegio">
            </div>
            <br>
            <h4>Nombre</h4>
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-envelope" style="color:red"></i></span>
              <input id="nombre" type="text" class="form-control" value="<?php echo $colegio->nombre ?>" placeholder="Ingrese nombre del colegio">
            </div>
            <br>
            <br>
          </form>
          <button  class="btn btn-success guardar pull-right"  />Editar</button>
          <span class=" ml-1 pull-right"> &nbsp; &nbsp; </span>
          <?php echo Html::link('administrador/colegios/', 'Volver', 'class="btn btn-default pull-right"') ?>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
$(".guardar").click(function(){
  var id = $("#colegio").val();
  var nombre = $("#nombre").val();
  var rbd = $("#rbd").val();
  $.ajax({
    type: "POST",
    cache: false,
    url: "../editar_colegio",
    data: {"id":id, "nombre":nombre, "rbd":rbd },
    success: function(result){
      if(result === 1){
        swal({
           title: "Colegio editado correctamente!",
           text: "En breves momentos serás redireccionado",
           type: "success",
           timer: 2500,
           onOpen: () => {
             swal.showLoading()
           }
         }).then((result) => {
           if (result.dismiss === 'timer') {
             window.location.href = "<?php echo PUBLIC_PATH.'administrador/colegios/' ?>";
           }
         });
      }else{
        swal(
              'Error al editar',
              'No se pudieron editar los datos del colegio, vuelva a intentar',
              'error'
            );
      }
    }
  })
});
</script>
