<!-- CSS se cargara en el template, primero carga el view luego el template -->
<?php Tag::css('../bower_components/datatables.net-bs/css/dataTables.bootstrap.min') ?>
<script type="text/javascript">
  $(document).ready(function() {
    var table = $('#tabla_productos').DataTable( {
      "ajax": {
               "url": "listar_usuarios",
               "dataSrc":"",
               "dataType": "json",
               "cache": false,
             },
      dom: 'Bfrtip',
      "buttons": [
         {"extend": 'excel', "text":'<i class="fa fa-download" aria-hidden="true"></i>&nbsp; &nbsp; Exportar Excel',"className": 'btn btn-success pull-center'}
      ],
      "columns": [
          { "data": "id" },
      	  { "data": "nombre" },
          { "data": "acciones"}
      ]
    });
    $("#tabla_productos").on("click", ".editar", function(){
      var id = $(this).attr("value");
      location.href = "http://localhost/evento/administrador/conferencistas/editar/"+id;
    });

    $(".agregar").click(function(){
      var id = $(this).attr("value");
      location.href = "http://localhost/evento/administrador/conferencistas/crear/";
    });

    $("#tabla_productos").on("click", ".eliminar", function(){
      var id = $(this).attr("value");
      $.ajax({
          type: "GET",
          cache: false,
          url: "<?php echo PUBLIC_PATH.'administrador/conferencistas/eliminar_usuario/' ?>"+id,
          success: function(result){
              if(result === 1){
                  swal({
                  type: 'success',
                  title: 'Edición correcta',
                  text: 'Ya lo estamos redirigiendo...',
                  timer: 2500,
                  onOpen: () => {
                    swal.showLoading()
                  }
                }).then((result) => {
                  if (result.dismiss === 'timer') {
                    window.location.href = "<?php echo PUBLIC_PATH.'administrador/conferencistas/' ?>";
                  }
                });
              }else{
                  swal(
                  'Error al eliminar',
                  'No se pudieron eliminar los datos, vuelva a intentar',
                  'error'
                );
              }
          }
      })
    });
  });
</script>
<div class="row">
  <div class="col-md-12">
    <div class="box box-danger">
      <div class="box-header">
        <i class="fa fa-users hidden"></i>
        <h3 class="box-title pull-left"> Lista de Usuarios </h3>
        <br>
        <br>
        <button class="btn btn-success agregar pull-right">Agregar nuevo usuario</button>
        <div class="table-responsive col-md-12">
          <table id="tabla_productos" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>ID</th>
		                <th>Nombre</th>
                    <th>Acciones</th>
                </tr>
            </thead>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
