<section class="page-title bg-title overlay-dark">
	<div class="container">
		<div class="row">
			<div class="col-12 text-center">
				<div class="title">
					<h3>Expositoras</h3>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="section single-speaker">
	<div class="container">
		<div class="block">
			<div class="row">
				<div class="col-lg-5 col-md-6 align-self-md-center">
					<div class="image-block">
            <?php echo Html::img('ana.png', 'speaker', 'class="img-fluid"') ?>
					</div>
				</div>
				<div class="col-lg-7 col-md-6 align-self-center">
					<div class="content-block">
						<div class="name">
							<h3>Ana María Arón Svigilsky</h3>
						</div>
						<div class="profession">
							<p>Psicología clínica y comunitaria</p>
						</div>
						<div class="details">
							<p>Ha desarrollado una línea de investigación en el tema del desarrollo de
								habilidades sociales y el clima social escolar. Está involucrada en el tema
								de la promoción del buen trato y la educación para la no-violencia, con varias
								publicaciones de libros y artículos en esta área. Ha participado como consultora
								en el Ministerio de Educación, el Ministerio de Salud y el Ministerio de Justicia,
								y también en organismos internacionales.
							<br>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="block">
			<div class="row">
				<div class="col-lg-5 col-md-6 align-self-md-center">
					<div class="image-block">
            <?php echo Html::img('carolina.png', 'speaker', 'class="img-fluid"') ?>
					</div>
				</div>
				<div class="col-lg-7 col-md-6 align-self-center">
					<div class="content-block">
						<div class="name">
							<h3>Carolina Hirmas Ready</h3>
						</div>
						<div class="profession">
							<p>Magíster en Estudios Sociales y Políticos de Latinoamérica</p>
						</div>
						<div class="details">
							<p>Profesora de Lengua y Literatura en educación secundaria; investigadora,
								magíster en Estudios Sociales y Políticos de Latinoamérica de la Universidad
								Alberto Hurtado. Desde el año 2012 es responsable del área de formación docente
								de la Organización de Estados Iberoamericanos en Chile. También se desempeña
								como académica de la Universidad Diego Portales en diversidad y convivencia escolar.
								Es formadora de formadores en temas de convivencia, comunidades de curso y resolución
								de conflictos. Ha coordinado y desarrollado numerosas investigaciones sobre
								innovaciones educativas para la Red Innovemos de la UNESCO, además de estudios
								sobre políticas públicas en diversidad cultural, convivencia democrática, patrimonio
								cultural y educación. Ejerció la docencia como profesora de castellano durante 10 años.
							<br>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="block">
			<div class="row">
				<div class="col-lg-5 col-md-6 align-self-md-center">
					<div class="image-block">
            <?php echo Html::img('cecilia.png', 'speaker', 'class="img-fluid"') ?>
					</div>
				</div>
				<div class="col-lg-7 col-md-6 align-self-center">
					<div class="content-block">
						<div class="name">
							<h3>Cecilia Cardemil Oliva</h3>
						</div>
						<div class="profession">
							<p>Master en Psicología</p>
						</div>
						<div class="details">
							<p>Profesora de Castellano, Universidad de Chile; Licenciada en Psicología,
								Université de la Sorbonne Nouvelle París V, Francia;  Master en Psicología,
								Universidad Católica de Lovaina, Bélgica. Integrante del equipo de asistencia
								técnica a escuelas en la Facultad de Educación de la Universidad Alberto Hurtado,
								se desempeña como académica en esa casa de estudios superiores.
							<br>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="block">
			<div class="row">
				<div class="col-lg-5 col-md-6 align-self-md-center">
					<div class="image-block">
            <?php echo Html::img('isidora.png', 'speaker', 'class="img-fluid"') ?>
					</div>
				</div>
				<div class="col-lg-7 col-md-6 align-self-center">
					<div class="content-block">
						<div class="name">
							<h3>Isidora Mena Edwards</h3>
						</div>
						<div class="profession">
							<p>Doctora en Ciencias de la Educación</p>
						</div>
						<div class="details">
							<p> Doctora en Ciencias de la Educación de la Pontificia Universidad
								Católica de Chile; Master en Formación de Valores, Universidad Virtual
								de Barcelona; Postítulo en Formación de Valores, Universidad Virtual
								de Barcelona; académica desde 1981 de la Escuela de Psicología,
								Pregrado y Magíster de la PUC. Actualmente, desde el proyecto Valoras,
								asesora y brinda apoyo para que las escuelas desarrollen un currículum
								integral que complemente  la dimensión académica con la formación
								socioafectiva y ética.
							<br>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="block">
			<div class="row">
				<div class="col-lg-5 col-md-6 align-self-md-center">
					<div class="image-block">
            <?php echo Html::img('neva.png', 'speaker', 'class="img-fluid"') ?>
					</div>
				</div>
				<div class="col-lg-7 col-md-6 align-self-center">
					<div class="content-block">
						<div class="name">
							<h3>Cecilia Cardemil Oliva</h3>
						</div>
						<div class="profession">
							<p>Neva Milicic Müller</p>
						</div>
						<div class="details">
							<p>Psicóloga especialista en educación y docente en la Pontificia Universidad
								Católica de Chile. Ha sido autora de numerosos publicaciones, tanto académicas
								como divulgativas, sobre la psicología infantil y el desarrollo emocional,
								a lo largo de una  trayectoria  en la que ha sido reconocida con el Premio
								Nacional del Colegio de Psicólogos, el  Premio  Visión  Educativa  David Weikart,
								además de ser  destacada  en 2005 y en 2007 por el diario El Mercurio como
								una de las 100 mujeres líderes de Chile.
							<br>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
