<!--============================
=            Banner            =
=============================-->

<section class="banner-two overlay-white-slant text-overlay">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-6">
				<!-- Content Block -->
				<div class="block">
					<h1>EventoSM</h1>
					<h2>Convivencia escolar</h2>
					<h3>2018</h3>
					<h6>19-04 Abril 2018 Santiago</h6>
					<!-- Action Button -->
					<a href="#" class="btn btn-main-md">Obtén tu entrada ahora</a>
				</div>
			</div>
		</div>
	</div>
</section>

<!--====  End of Banner  ====-->

<!--===========================
=            About            =
============================-->

<section class="section about">
	<div class="container">
		<div class="row">
			<div class="col-lg-5 col-md-6 align-self-center">
				<div class="image-block two bg-about">
					<img class="img-fluid" src="/images/speakers/featured-speaker-two.jpg" alt="">
				</div>
			</div>
			<div class="col-lg-6 col-md-6 align-self-center ml-lg-auto">
				<div class="content-block">
					<h2><span class="alternate">Convivencia Escolar</span></h2>
					<div class="description-one">
            <h3>Objetivo</h3>
						<p>
							“El clima de convivencia escolar es el factor que más influye en los resultados del SIMCE, con un aumento de hasta 42 puntos” - Agencia de la Calidad
						</p>
					</div>
					<div class="description-two">
            <h3>Dirigido a</h3>
						<p>“Directores, encargados de convivencia escolar, académicos, coordinadores, jefes de UTP y docentes de establecimientos públicos y particulares subvencionados adscritos a ley Sep.”</p>
					</div>
					<ul class="list-inline">
						<li class="list-inline-item">
							<a href="#" class="btn btn-main-md">Adquirir entrada</a>
						</li>
						<li class="list-inline-item">
							<!--<a href="#" class="btn btn-transparent-md">Read more</a>-->
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>

<!--====  End of About  ====-->

<section class="speakers-full-width">
	<div class="container-fluid p-0">
		<div class="row">
			<div class="col-12">
				<!-- Speaker Slider -->
				<div class="speaker-slider">
					<div class="speaker-image">
						<img src="/eventosm/img/ana.png" alt="speaker" class="img-fluid">
						<div class="primary-overlay text-center">
							<h5>ANA MARÍA ARÓN SVIGILSKY</h5>
							<p>Psicología clínica y comunitaria</p>
						</div>
					</div>
					<div class="speaker-image">
						<img src="/eventosm/img/carolina.png" alt="speaker" class="img-fluid">
						<div class="primary-overlay text-center">
							<h5>CAROLINA HIRMAS READY</h5>
							<p>Magíster en Estudios Sociales y Políticos de Latinoamérica</p>
						</div>
					</div>
					<div class="speaker-image">
						<img src="/eventosm/img/cecilia.png" alt="speaker" class="img-fluid">
						<div class="primary-overlay text-center">
							<h5>CECILIA CARDEMIL OLIVA</h5>
							<p>Master en Psicología</p>
						</div>
					</div>
					<div class="speaker-image">
						<img src="/eventosm/img/isidora.png" alt="speaker" class="img-fluid">
						<div class="primary-overlay text-center">
							<h5>ISIDORA MENA EDWARDS</h5>
							<p>Doctora en Ciencias de la Educación</p>
						</div>
					</div>
					<div class="speaker-image">
						<img src="/eventosm/img/neva.png" alt="speaker" class="img-fluid">
						<div class="primary-overlay text-center">
							<h5>NEVA MILICIC MÜLLER</h5>
							<p>Psicóloga especialista en educación</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>


<section id="section-ajenda" class="section-wrapper section-ajenda">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-title">
                        <h1>PROGRAMA</h1>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="session">
                        <time>8:30AM</time>
                        <h3><i>Acreditación</i></h3>
                    </div>
                    <!-- .session -->

                    <div class="session">
                        <time>9:00 - 9:15</time>
                        <h3><i>Palabras de bienvenida</i></h3>
                        <h3>Francisco Tepper <span>DIRECTOR GENERAL DE SM</span></h3>
                    </div>
                    <!-- .session -->

                    <div class="session">
                        <time>9:00 - 10:00</time>
                        <h3><i>Introducción</i></h3>
                        <h3>Los Indicadores de Desarrollo Personal y Social (IDPS) como desafío a las Instituciones Educativas.</h3>
                        <h3>Isidora Mena Edwards <span>DOCTORA EN CIENCIAS DE LA EDUCACIÓN</span></h3>
                    </div>
                    <!-- .session -->

                </div>
                <div class="col-md-4">

                    <div class="session">
                        <time>10:00 - 11:00</time>
                        <h3><i>Conferencia</i></h3>
                        <h3>Climas sociales tóxicos y nutritivos en el contexto escolar.</h3>
                        <h3>Ana María Arón Svigilsky <span>DOCTORA EN CIENCIAS DE LA EDUCACIÓN</span></h3>
                    </div>
                    <!-- .session -->

                    <div class="session">
                        <time>11:00 - 11:30</time>
                        <h3><i>Coffee Break</i></h3>
                    </div>
                    <!-- .session -->




                </div>
                <div class="col-md-4">
                  <div class="session">
                      <time>11:30 - 13:00</time>
                      <h3><i>Mesa redonda</i></h3>
                      <h3>Importancia del aprendizaje socioemocional en la gestión del clima social (basados en las investigaciones de la colección Somos Maestros).</h3>
                      <ul>
                        <h3>Clima social</h3>
                        <h3>Relación familia</h3>
                        <h3>Resolución</h3>
                        <h3>Inclusión educativa</h3>
                      </ul>
                      <h3>Neva Milicic Müller <span>PSICÓLOGA ESPECIALISTA EN EDUCACIÓN</span></h3>
                      <h3>Isidora Mena Edwards <span>PSICÓLOGA ESPECIALISTA EN EDUCACIÓN</span></h3>
                      <h3>Carolina Hirmas Ready <span>MAGÍSTER EN ESTUDIOS SOCIALES Y POLÍTICOS DE LATINOAMERICA</span></h3>
                      <h3>Cecilia Cardemil Oliva<span>MASTER EN PSICOLOGÍA</span></h3>
                  </div>
                  <!-- .session -->


                    <!-- .session -->


                </div>
            </div>
        </div>

    </section>

<!--====  End of Schedule  ====-->

<!--=============================
=            Feature            =
==============================-->

<section class="ticket-feature">
	<div class="container-fluid m-0 p-0">
		<div class="row p-0 m-0">
			<div class="col-lg-7 p-0 m-0">
				<div class="block bg-timer overlay-dark text-center">
					<div class="section-title white m-0">
						<h3>Audiencia limitada <span class="alternate">Asientos</span></h3>
						<p>Adquiere tu entrada antes de que se agoten</p>
					</div>
					<!-- Coundown Timer -->
					<div class="timer"></div>
					<a href="#" class="btn btn-main-md">Adquirir entradas</a>
				</div>
			</div>
			<div class="col-lg-5 p-0">
				<div class="block-2">
					<div class="row no-gutters">
						<div class="col-6">
							<!-- Service item -->
							<div class="service-item">
								<i class="fa fa-microphone"></i>
								<h5>5 Expositoras</h5>
							</div>
						</div>
						<div class="col-6">
							<!-- Service item -->
							<div class="service-item">
								<i class="fa fa-flag"></i>
								<h5>300 + Asientos</h5>
							</div>
						</div>
						<div class="col-6">
							<!-- Service item -->
							<div class="service-item">
								<i class="fa fa-ticket"></i>
								<h5>300 entradas</h5>
							</div>
						</div>
						<div class="col-6">
							<!-- Service item -->
							<div class="service-item">
								<i class="fa fa-calendar"></i>
								<h5>Evento completo</h5>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!--====  End of Feature  ====-->


<!--==========================
=            News            =
===========================-->

<!--====  End of News  ====-->

<!--=============================
=            Gallery            =
==============================-->


<!--====  End of Gallery  ====-->

<!--===================================
=            Pricing Table            =
====================================-->

<section class="section pricing two">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="section-title">
					<h3>Obtener <span class="alternate">entradas</span></h3>
					<p>Puedes adquirirla sin costo alguno</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4 col-md-6">

			</div>
			<div class="col-lg-4 col-md-6">
				<!-- Pricing Item -->
				<div class="pricing-item featured">
					<div class="pricing-heading text-center">
						<!-- Title -->
						<div class="title">
							<h6>Estandar</h6>
						</div>
						<!-- Price -->
						<div class="price">
							<h2>Gratuito</h2>
						</div>
					</div>
					<div class="pricing-body">
						<?php echo $config->cupos ?>

					</div>
					<div class="pricing-footer text-center">
						<a href="#" class="btn btn-main-md">Adquirir una entrada</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 m-auto">

			</div>
		</div>
	</div>
</section>

<!--====  End of Pricing Table  ====-->

<!--================================
=            Google Map            =
=================================-->

<section class="map new">
	<!-- Google Map -->
	<div id="mapa"></div>
  <div class="row">
      <div class="col-md-12">
          <div id="map" class="googleMap"></div>
      </div>
  </div>
</section>

<!--====  End of Google Map  ====-->
<input id="lugar"  type="hidden"   class="hidden" value="<?php echo $config->lugar?>">
<input id="latitud" type="hidden"  class="hidden" value="<?php echo $config->latitud?>">
<input id="longitud" type="hidden" class="hidden" value="<?php echo $config->longitud?>">
