<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-xs-12 col-sm-8">
    <div class="box box-solid">
            <div class="box-header with-border">
              <i class="fa fa-text-width"></i>

              <h3 class="box-title">Programa del evento</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <dl class="dl-horizontal">
                <?php echo $programa->contenido ?>
                <hr>
                <?php echo Html::link('administrador/programa/editar', '<i class="fa fa-edit"></i> Editar Programa', 'class="btn btn-primary"') ?>
              </dl>
            </div>
            <!-- /.box-body -->
          </div>

  </div>
  <div class="col-sm-2"></div>
</div>
