<div class="row">
  <div class="col-sm-12">
    <div class="box box-primary">
      <div class="box-header">
        <i class="fa fa-users hidden"></i>
        <h3 class="box-title"> Banner principal </h3>
        <div class="box-body">
          <?php View::content() ?>
          <!-- Cargar imagen que tiene el sistema asociado -->
          <?php echo Html::linkAction('editar', 'Editar Banner', 'class="btn btn-primary pull-left"') ?>
          <br>
          <hr>
          <?php echo Html::img('upload/defecto.png', 'banner', 'class="baner"') ?>
        </div>
      </div>
    </div>
  </div>
</div>
