<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="box box-primary">
      <div class="box-header">
        <i class="fa fa-users hidden"></i>
        <h3 class="box-title"> Configuración general </h3>
        <br><p>
          <?php echo Html::link('administrador/configuracion/editar', '<i class="fa fa-cog pull-left"> Editar configuración </i>', 'class="btn btn-success"') ?>
        <br>
        <hr>
        <p>Nombre del evento: <b><?php echo $evento->nombre ?></b></p>
        <p>Subtítulo: <b><?php echo $evento->subtitulo ?></b></p>
        <ul>
          <li>Precio: <b><?php echo '$'.$evento->precio ?></b></li>
          <li>Cupos: <b><?php echo $evento->cupos ?></b></li>
          <li>Fecha: <b><?php echo $evento->fecha ?></b></li>
          <li>Hora: <b><?php echo $evento->hora_inicio.' - '.$evento->hora_final ?></b></li>
          <li>Lugar: <b><?php echo $evento->lugar ?></b></li>
        </ul>
        <h3 class="text-center">Objetivo</h3>
        <p>
          <?php echo $evento->objetivo ?>
        </p>
      </div>
    </div>
  </div>
  <div class="col-sm-2"></div>
</div>
