<?php echo Tag::js("selectize/js/standalone/selectize");?>
<br>
<section class="section about">
	<div class="container">
		<div class="row">
			<div class="col-lg-2 col-md-2"></div>
			<div class="col-lg-8 col-md-8 align-self-center">
        <h3 class="text-center">Formulario de inscripción</h3>
        <div class="form-group row">
              <label class="col-xs-12 col-3 col-form-label">Región</label>
              <div class="col-xs-12 col-9">
                <select id="region" class="form-control main">
                  <option value="" disabled selected >Seleccione...</option>
                  <?php foreach($region as $key => $valor): ?>
                    <option value="<?php echo $valor->id ?>"><?php echo $valor->nombre ?></option>
                  <?php endforeach ?>
                </select>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-3 col-form-label">Comuna</label>
              <div class="col-9">
                <select id="comuna" class="form-control main">
                  <option value="" disabled selected >Seleccione...</option>
                </select>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-3 col-form-label">Colegio o Institución</label>
              <div class="col-9">
                <select id="colegio" class="main" selectize>
                  <option value=""></option>
                  <?php foreach($colegios as $key => $valor): ?>
                    <option value="<?php echo $valor->rbd ?>"><b>Rbd</b> - <?php echo $valor->rbd ?> - <?php echo $valor->nombre ?></option>
                  <?php endforeach ?>
                </select>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-3 col-form-label">Cantidad de entradas</label>
              <div class="col-9">
                <select id="entradas" class="form-control main">
                  <?php for ($i=1; $i < 6; $i++): ?>
                    <option value="<?php echo $i ?>"><?php echo $i ?></option>
                  <?php endfor ?>
                </select>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-3 col-form-label">Correo para recibir comprobante</label>
              <div class="col-9">
                <input id="correo" type="email" class="form-control main" placeholder="correo@correo.cl">
              </div>
              <br>
            </div>
            <div class="form-group row">
              <div class="col-12">
								<ul class="list-inline">
									<li class="list-inline-item">
										<button id="guardar" name="button" class="btn btn-main-md">Solicitar entradas</button>
									</li>
									<li class="list-inline-item">
										<?php echo Html::link('', 'Volver a la página de inicio', 'class="btn btn-transparent-md"') ?>
									</li>
								</ul>
              </div>
            </div>
			</div>
			<div class="col-lg-2 col-md-2"></div>
		</div>
	</div>
</section>
<script type="text/javascript">
  $(document).ready(function(){
    $('#colegio').selectize({
      create: true,
      sortField: 'text',
      render: {
        option_create: function(data, escape) {
          var addString = 'Agregar';
          return '<div class="create">' + addString + ' <strong>' + escape(data.input) + '</strong>&hellip;</div>';
        }
      }
    });
   $("#region").val(13);
    $.ajax({
    type : "post",
    cache : false,
    url : "<?php echo PUBLIC_PATH.'inscripcion/cargarComunas' ?>",
    data : {"region" : 13},
    success : function(result){
        $.each(result, function(i,val){
      $("#comuna").append("<option value='"+val.id+"'>"+val.nombre+"</option>");
        });
      }
    });
    $("#region").on("change", function(){
  	    var region = $(this).val();
  	    $("#comuna").find("option").remove();
  	    $("#comuna").append("<option value='sl' disabled selected>Seleccione...</option>");
  	    $.ajax({
    		type : "post",
    		cache : false,
    		url : "<?php echo PUBLIC_PATH.'inscripcion/cargarComunas' ?>",
    		data : {"region" : region},
    		success : function(result){
    		    $.each(result, function(i,val){
    			$("#comuna").append("<option value='"+val.id+"'>"+val.nombre+"</option>");
    		    });
    		  }
  	    });
	  });
    $("#guardar").click(function(){
      var region = $("#region").val();
      var comuna = $("#comuna").val();
      var cargo = $("#cargo").val();
      var colegio = $("#colegio").val();
      var entradas = $("#entradas").val();
      var correo = $("#correo").val();
      if(comuna == null){
        swal(
          'Debe seleccionar una comuna',
          'Elija la comuna que corresponde',
          'info'
        )
        return;
      }
      if(colegio == ''){
        swal(
          'Debe seleccionar un colegio',
          'Elija el colegio que corresponde',
          'info'
        )
        return;
      }
      if(correo == ''){
        swal(
          'Debe colocar un correo',
          'Coloque un correo válido, ejemplo: correo@gmail.com',
          'info'
        )
        return;
      }else{
        if(correo.indexOf('@', 0) == -1 || correo.indexOf('.', 0) == -1) {
          swal(
            'Debe colocar un correo válido',
            'Coloque un correo válido, ejemplo: correo@gmail.com',
            'error'
          )
          return;
        }
      }

      $.ajax({
        type: 'post',
        url: '<?php echo PUBLIC_PATH.'inscripcion/solicitarInscripcion' ?>',
        cache: false,
        data: {"region":region, "comuna":comuna, "cargo":cargo, "colegio":colegio, "entradas":entradas, "correo":correo},
        success: function(result){
          console.log(result);
          if(result[0] === 1){
            swal({
                  type: 'success',
                  title: 'Usted puede hacer la compra de sus entradas',
                  text: 'Gracias por su confianza, ya lo estamos redirigiendo...',
                  timer: 1000,
                  onOpen: () => {
                    swal.showLoading()
                  }
                }).then((result) => {
                  if (result.dismiss === 'timer') {
                    window.location.href = "<?php echo PUBLIC_PATH.'inscripcion/invitados' ?>";
                  }
                });
          }
          if(result[0] === 2){
            console.log('Ya no puede hacer ninguna compra');
            swal(
              'Usted ya supero el máximo de compra por colegio',
              'El numero de entradas compradas son: '+result[1],
              'error'
            )
          }
          if(result[0] === 3){
            console.log('Tiene disponible pero supera por las que solicita actualmente');
            swal(
              'Tiene disponible',
              'Usted tiene disponibilidad de '+ result[1] +' entrada(s) pero supera por la cantidad de entradas que solicita',
              'error'
            )
          }
          if(result[0] === 4){
            console.log('Tiene disponible');
            swal({
                  type: 'success',
                  title: 'Usted puede hacer la compra de sus entrada(s)',
                  text: 'Gracias por su confianza, ya lo estamos redirigiendo...',
                  timer: 1000,
                  onOpen: () => {
                    swal.showLoading()
                  }
                }).then((result) => {
                  if (result.dismiss === 'timer') {
                    window.location.href = "<?php echo PUBLIC_PATH.'inscripcion/invitados' ?>";
                  }
                });
          }
					if(result[0] === 6){
						console.log('No hay disponibilidad de cupos para este evento');
						swal(
              'No hay disponibilidad',
              'Se agotaron las invitaciones o eligió un monto superior al disponible para este evento',
              'error'
            )
					}
        }
      });
    });
  })
</script>
