<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="card text-white bg-info mb-3" style="max-width: 100%">
      <div class="card-body">
        <h4 class="card-title">Coloca tus datos para el pago</h4>
        <div class="form-group">
          <?php View::content() ?>
          <?php echo Form::open('inscripcion/procesar_pago') ?>
            <label>Usuario</label>
            <?php echo Form::text('correo', 'class="form-control" placeholder="tucorreo@correo.com"') ?>
            <label>Banco</label>
            <select id="banco" name="banco" class="form-control">
            </select>
            <br>
            <?php echo Form::submit('Entrar', 'class="btn btn-success"') ?>
          <?php echo Form::close() ?>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-2"></div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    var datos;
    $.ajax({
      type: 'GET',
      cache: false,
      url: 'http://localhost/evento/inscripcion/bancos_khipu',
      success: function(result){
        datos = JSON.parse(result);
        $.each(datos['banks'], function(i, val){
          if(val.type == 'Persona'){
            $("#banco").append("<option value='"+val.id+"'>"+val.name+"</option>");
          }
        })
      }
    })
  })
</script>
