<br>
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="card text-white bg-info mb-3">
        <div class="card-body">
          <h4 class="card-title">Realizar pago</h4>
          <p class="start-khipu"><img src="https://s3.amazonaws.com/static.khipu.com/buttons/2015/200x75-transparent.png" id="pay-button"/></p>
        </div>
    </div>
  </div>
  <div class="col-sm-2"></div>
  <div id="khipu-chrome-extension-div"></div>
</div>
<script src="//storage.googleapis.com/installer/khipu-2.0.js"></script>
<script type="text/javascript">
  window.onload = function (){
    KhipuLib.startKhipu('<?php echo $urlpago ?>','<?php echo $idpago;?>','<?php echo $terminal ?>', '#pay-button');
  }
</script>
